version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=fiapPASSWORD123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - sqlnet
    restart: always
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:

networks:
  sqlnet:
