name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image API
      run: docker build . --file Dockerfile --tag my-image-api:latest

    - name: Start Database with Docker Compose
      run: docker-compose -f docker-compose.yml up -d
