name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "SenhaSegura123!"
        ports:
          - 1433:1433
        options: > 
          --network-alias sqlserver

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Build the Docker image API
        run: docker build . --file Dockerfile --tag my-image-api:latest

      - name: Create appsettings.json
        run: |
          mkdir -p Infrastructure
          echo '{
            "ConnectionStrings": {
              "DefaultConnection": "Server=localhost,1433;Database=TestDb;User Id=sa;Password=SenhaSegura123!;TrustServerCertificate=True"
            }
          }' > Infrastructure/appsettings.json

      - name
