name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "SenhaSegura123!"
        ports:
          - 1433:1433
        options: > 
          --network-alias sqlserver

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build the Docker image API
        run: docker build . --file Dockerfile --tag my-image-api:latest

      - name: Wait for SQL Server to be ready
        run: |
          for i in {30..0}; do
            if echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'SenhaSegura123!' > /dev/null; then
              break
            fi
            echo 'SQL Server is starting...'
            sleep 1
          done

      - name: Run specific integration tests
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TestDb;User Id=sa;Password=SenhaSegura123!" 
        run: dotnet test "Testes/Integracao/IntegracaoContato.cs" --logger "trx;LogFileName=test_results.trx"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag API Image for Docker Hub
        run: docker tag my-image-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-api:latest
        
      - name: Push API Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-api:latest
