name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image API
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image Banco de Dados
      run: docker build . --file docker-compose --tag my-image-name:$(date +%s)
